production:
 build: .
 ports:
  - "9000:9000"
 extra_hosts:
  - "paulnebel.com:127.0.0.1"
 links:
  - nginx
 environment:
  - BROWSER=google-chrome
  - VIRTUAL_HOST=paulnebel.com
 command: sh ./shell/scripts/post-run-live.sh

serve-dev:
 build: .
 dockerfile: dev-Dockerfile
 volumes:
  - $PWD/..://home/dogfish/app
 ports:
  - "9000:9000"
 extra_hosts:
  - "paulnebel.com:127.0.0.1"
 links:
  - nginx
 environment:
  - BROWSER=google-chrome
  - VIRTUAL_HOST=paulnebel.com
 command: sh ./shell/scripts/post-run-dev.sh

nginx:
 image: jwilder/nginx-proxy
 container_name: poc_nginx
 ports:
  - "80:80"
 volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro

serve-dist:
 build: .
 dockerfile: dev-Dockerfile
 volumes:
  - $PWD/..://home/dogfish/app
 ports:
  - "9000:9000"
 extra_hosts:
  - "paulnebel.com:127.0.0.1"
 links:
  - nginx
 environment:
  - BROWSER=google-chrome
  - VIRTUAL_HOST=paulnebel.com
 command: sh ./shell/scripts/post-run-live.sh

test:
 build: .
 dockerfile: dev-Dockerfile
 volumes:
  - .://home/redjam/app
 ports:
  - "9000:9000"
 extra_hosts:
  - "paulnebel.com:127.0.0.1"
 links:
  - nginx
 environment:
  - BROWSER=google-chrome
  - VIRTUAL_HOST=paulnebel.com
 command: sh ./shell/scripts/post-run-test.sh