production:
 build: .
 ports:
  - "9000:9000"
 links:
  - nginx
 environment:
  - BROWSER=google-chrome
  - VIRTUAL_HOST=paulnebel.com
  - VIRTUAL_PORT=9000
 command: sh ./shell/scripts/post-run-live.sh

serve-dev:
 build: .
 dockerfile: dev-Dockerfile
 volumes:
  - $PWD/..://home/dogfish/app
 ports:
  - "9000:9000"
  - "35729:35729"
 environment:
  - BROWSER=google-chrome
 command: sh ./shell/scripts/post-run-dev.sh

nginx:
 image: jwilder/nginx-proxy
 ports:
  - "80:80"
 volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro

serve-dist:
 build: .
 dockerfile: dev-Dockerfile
 volumes:
  - $PWD/..://home/dogfish/app
 ports:
  - "9000:9000"
 environment:
  - BROWSER=google-chrome
 command: sh ./shell/scripts/post-run-live.sh